"use client";

import { useState } from 'react';
import type { SuggestedGame } from '@/lib/types';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { ThumbsUp, ThumbsDown, Info, Bot } from 'lucide-react';
import { getGameDetails } from '@/app/actions';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

interface RecommendationDisplayProps {
  recommendations: SuggestedGame[];
  isLoading: boolean;
  error: string | null;
}

export function RecommendationDisplay({ recommendations, isLoading, error }: RecommendationDisplayProps) {

  const [details, setDetails] = useState<{ [key: string]: string }>({});
  const [isDetailsLoading, setIsDetailsLoading] = useState<string | null>(null);

  const handleFetchDetails = async (gameTitle: string) => {
    if(details[gameTitle]) return;

    setIsDetailsLoading(gameTitle);
    const result = await getGameDetails(gameTitle);
    setDetails(prev => ({...prev, [gameTitle]: result.gameDetails}));
    setIsDetailsLoading(null);
  }

  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="space-y-4">
          {[...Array(3)].map((_, i) => (
            <Card key={i}>
              <CardHeader>
                <Skeleton className="h-6 w-3/4" />
              </CardHeader>
              <CardContent>
                <Skeleton className="h-4 w-full mb-2" />
                <Skeleton className="h-4 w-5/6" />
              </CardContent>
              <CardFooter>
                 <Skeleton className="h-8 w-24" />
              </CardFooter>
            </Card>
          ))}
        </div>
      );
    }
    
    if (error) {
      return <div className="text-destructive text-center p-8">{error}</div>;
    }
    
    if (recommendations.length === 0) {
      return (
        <div className="text-center p-8 flex flex-col items-center justify-center h-full animate-fade-in">
            <div className="relative mb-6">
              <div className="absolute inset-0 bg-primary/20 blur-2xl rounded-full animate-pulse" />
              <Bot className="relative w-16 h-16 text-muted-foreground" />
            </div>
            <h3 className="text-xl font-headline font-semibold mb-2">Ready for your Game-Plan</h3>
            <p className="text-muted-foreground mt-2 max-w-sm">
                Hi! I'm <span className="font-semibold text-primary">Clear</span>. Fill in your schedule, click "Analyze & Suggest", and I'll find the best games for you to play from your library.
            </p>
            <Card className="mt-6 text-sm text-left p-4 bg-muted/30 border-border/50 max-w-sm w-full">
                <CardTitle className="text-base font-headline mb-2">Coming Soon</CardTitle>
                <CardDescription className="text-xs">
                Direct Steam API integration, wishlist analysis, and sharing recommendations with friends are coming soon!
                </CardDescription>
            </Card>
        </div>
      )
    }

    return (
      <div className="space-y-3">
        {recommendations.map((game, index) => (
          <Card 
            key={game.gameTitle} 
            className="bg-card/50 border-border/50 hover:shadow-md transition-all duration-200 animate-slide-up"
            style={{ animationDelay: `${index * 0.1}s` }}
          >
            <CardHeader className="pb-3">
              <CardTitle className="font-headline text-lg">{game.gameTitle}</CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <p className="text-sm text-muted-foreground leading-relaxed">{game.reason}</p>
            </CardContent>
            <CardFooter className="justify-between pt-3 border-t border-border/50">
                <Dialog>
                    <DialogTrigger asChild>
                        <Button 
                          variant="outline" 
                          size="sm" 
                          onClick={() => handleFetchDetails(game.gameTitle)}
                          className="hover:bg-accent/10 hover:border-accent/50 transition-colors"
                        >
                            <Info className="w-4 h-4 mr-2"/>
                            Details
                        </Button>
                    </DialogTrigger>
                    <DialogContent className="max-w-2xl">
                        <DialogHeader>
                        <DialogTitle className="font-headline text-xl">{game.gameTitle}</DialogTitle>
                        <DialogDescription>
                            Summary generated by Clear based on web data.
                        </DialogDescription>
                        </DialogHeader>
                        <div className="py-4 text-sm max-h-[60vh] overflow-y-auto prose prose-sm dark:prose-invert">
                            {isDetailsLoading === game.gameTitle && <Skeleton className="h-24 w-full" />}
                            {details[game.gameTitle] && <p className="leading-relaxed">{details[game.gameTitle]}</p>}
                        </div>
                    </DialogContent>
                </Dialog>

                <div className="flex gap-2">
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      aria-label="Good suggestion"
                      className="hover:bg-green-500/10 hover:text-green-500 transition-colors"
                    >
                        <ThumbsUp className="w-4 h-4" />
                    </Button>
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      aria-label="Bad suggestion"
                      className="hover:bg-red-500/10 hover:text-red-500 transition-colors"
                    >
                        <ThumbsDown className="w-4 h-4" />
                    </Button>
                </div>
            </CardFooter>
          </Card>
        ))}
      </div>
    );
  };

  return (
    <Card className="h-full flex flex-col bg-card/80 backdrop-blur-sm border-border/50 shadow-lg">
      <CardHeader className="border-b border-border/50">
        <CardTitle className="font-headline text-xl flex items-center gap-2">
          <div className="p-2 rounded-lg bg-primary/10">
            <Bot className="w-5 h-5 text-primary" />
          </div>
          Clear's Game-Plan
        </CardTitle>
        <CardDescription className="mt-2">
          Here are the games from your library that best fit your schedule and playstyle, handpicked by Clear.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex-grow overflow-y-auto pr-2 pt-4">
        {renderContent()}
      </CardContent>
    </Card>
  );
}
